# Generated by Django 4.0.2 on 2022-02-08 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('attributes', models.JSONField(verbose_name='attributes')),
                ('tendencies', models.JSONField(verbose_name='tendencies')),
                ('avatar', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='game_name', max_length=10)),
                ('game_stats', models.JSONField(default=dict)),
                ('player_one_stats', models.JSONField(default=dict)),
                ('player_two_stats', models.JSONField(default=dict)),
                ('player_one_score', models.IntegerField(default=0)),
                ('player_two_score', models.IntegerField(default=0)),
                ('player_one_squad', models.JSONField(default=dict)),
                ('player_two_squad', models.JSONField(default=dict)),
                ('date', models.DateField(blank=True, null=True)),
                ('player_one', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='player_one', to='blacktop.user')),
                ('player_two', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='player_two', to='blacktop.user')),
                ('winner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='winner', to='blacktop.user')),
            ],
        ),
    ]
