# Generated by Django 4.0.2 on 2022-02-12 20:03

from django.db import migrations


def seed(apps, schema_editor):
    Player = apps.get_model('blacktop', 'Player')
    Player(name="Michael Jordan",
           nickname="Air Jordan",
           height=78,
           attributes={
               'offense': {
                   'layup': 98,
                   'post_shot': 70,
                   'mid_range': 99,
                   'three': 78,
                   'handles': 88,
                   'pass': 82,
                   'off_rebound': 58,
                   'dunk': 97
               },
               'defense': {
                   'def_rebound': 63,
                   'inside_defense': 70,
                   'outside_defense': 98,
                   'steal': 91,
                   'block': 59,
                   'post_defense': 70
               },
               'physical': {
                   'speed': 86,
                   'vertical': 96,
                   'strength': 68
               }
           }, tendencies={
               'offense': {
                   'shoot_mid': 77,
                   'shoot_three': 47,
                   'pass': 72,
                   'attack_rim': 94,
                   'post_up': 95
               },
               'defense': {
                   'steal': 65,
                   'block': 70,
                   'intercept': 70
               }
           }, avatar="https://www.gannett-cdn.com/presto/2020/04/18/USAT/f5e5f735-2eff-426c-a783-baca6d2872ab-05.JPG?crop=984,1012,x0,y0&width=1588",
           description="Michael Jordan is a former professional American basketball player, Olympic athlete, businessperson and actor. Considered one of the best basketball players ever, he dominated the sport from the mid-1980s to the late 1990s",
           image="https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F20%2F2020%2F04%2F21%2Fmichael-jordan-3-1.jpg",
           tier=1).save()
    Player(name="Lebron James",
           nickname="King",
           height=81,
           attributes={
                'offense': {
                    'layup': 98,
                    'post_shot': 88,
                    'mid_range': 81,
                    'three': 76,
                    'handles': 86,
                    'pass': 87,
                    'off_rebound': 75,
                    'dunk': 95
                },
               'defense': {
                    'def_rebound': 79,
                    'inside_defense': 80,
                    'outside_defense': 96,
                    'steal': 62,
                    'block': 52,
                    'post_defense': 79
                },
               'physical': {
                    'speed': 89,
                    'vertical': 84,
                    'strength': 92
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 47,
                   'shoot_three': 57,
                   'pass': 65,
                   'attack_rim': 81,
                   'post_up': 55
               },
               'defense': {
                   'steal': 31,
                   'block': 70,
                   'intercept': 69
               }
           }, avatar="https://sportshub.cbsistatic.com/i/r/2020/03/25/5a9bf93f-1688-4251-af07-6caace3ef679/thumbnail/1200x675/8016dc48407290c004104a97fef5cb1b/lebron.jpg",
           description="LeBron James is an American basketball player with the Los Angeles Lakers. James first garnered national attention as the top high school basketball player in the country. With his unique combination of size, athleticism and court vision, he became a four-time NBA MVP.",
           image="https://static01.nyt.com/images/2020/06/10/us/politics/10lebron-voters/10lebron-voters-mediumSquareAt3X.jpg",
           tier=1).save()

    Player(name="Tim Duncan",
           nickname="Big Fundamental",
           height=83,
           attributes={
                'offense': {
                    'layup': 79,
                    'post_shot': 93,
                    'mid_range': 95,
                    'three': 76,
                    'handles': 59,
                    'pass': 82,
                    'off_rebound': 94,
                    'dunk': 85
                },
               'defense': {
                    'def_rebound': 95,
                    'inside_defense': 99,
                    'outside_defense': 69,
                    'steal': 79,
                    'block': 96,
                    'post_defense': 95
                },
               'physical': {
                    'speed': 68,
                    'vertical': 80,
                    'strength': 96
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 67,
                   'shoot_three': 37,
                   'pass': 65,
                   'attack_rim': 90,
                   'post_up': 99
               },
               'defense': {
                   'steal': 40,
                   'block': 80,
                   'intercept': 75
               }
           }, avatar="https://www.nydailynews.com/resizer/IT80S2462HG71fa8Gn-dW82rrGI=/415x276/top/arc-anglerfish-arc2-prod-tronc.s3.amazonaws.com/public/CEZW2RCG7LMRM2QXPE2OQL3F5Y.jpg",
           description="Timothy Theodore Duncan (born April 25, 1976) is an American former professional basketball player and coach. Nicknamed ' the Big Fundamental ', he is widely regarded as the greatest power forward of all time and one of the greatest players in NBA history.",
           image="https://media.newyorker.com/photos/590978241c7a8e33fb38fb1d/master/w_2560%2Cc_limit/Crouch-Duncan.jpg",
           tier=1).save()
    Player(name="Giannis Antetokounmpo",
           nickname="Greak Freak",
           height=83,
           attributes={
                'offense': {
                    'layup': 98,
                    'post_shot': 79,
                    'mid_range': 79,
                    'three': 70,
                    'handles': 87,
                    'pass': 84,
                    'off_rebound': 58,
                    'dunk': 91
                },
               'defense': {
                    'def_rebound': 92,
                    'inside_defense': 91,
                    'outside_defense': 95,
                    'steal': 59,
                    'block': 82,
                    'post_defense': 92
                },
               'physical': {
                    'speed': 90,
                    'vertical': 85,
                    'strength': 94
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 67,
                   'shoot_three': 47,
                   'pass': 70,
                   'attack_rim': 95,
                   'post_up': 84
               },
               'defense': {
                   'steal': 50,
                   'block': 90,
                   'intercept': 69
               }
           }, avatar="https://library.sportingnews.com/2021-12/giannis-antetokounmpo-milwaukee-bucks_yvv75rnfa24r105azbf093kjx.png",
           description="Giannis Sina Ugo Antetokounmpo is a Greek professional basketball player for the Milwaukee Bucks of the National Basketball Association (NBA). Antetokounmpo's nationality, in addition to his size, speed and ball-handling skills have earned him the nickname 'Greek Freak'",
           image="https://library.sportingnews.com/2021-11/giannis-antetokounmpo-11122021-ftr-getty_s33eyyrb2ogz1gf18h024rfp9.jpeg",
           tier=1).save()

    Player(name="Larry Bird",
           nickname="Legend",
           height=81,
           attributes={
                'offense': {
                    'layup': 72,
                    'post_shot': 94,
                    'mid_range': 96,
                    'three': 96,
                    'handles': 79,
                    'pass': 94,
                    'off_rebound': 61,
                    'dunk': 45
                },
               'defense': {
                    'def_rebound': 77,
                    'inside_defense': 85,
                    'outside_defense': 88,
                    'steal': 75,
                    'post_defense': 85,
                    'block': 47
                },
               'physical': {
                    'speed': 90,
                    'vertical': 85,
                    'strength': 94
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 84,
                   'shoot_three': 84,
                   'pass': 75,
                   'attack_rim': 70,
                   'post_up': 84
               },
               'defense': {
                   'steal': 65,
                   'block': 40,
                   'intercept': 69
               }
           }, avatar="https://m.media-amazon.com/images/M/MV5BMTY0NzUyNzkyOF5BMl5BanBnXkFtZTcwNzczNDk5Nw@@._V1_.jpg",
           description="Larry Joe Bird (born December 7, 1956) is an American former professional basketball player, coach and executive in the National Basketball Association (NBA). Nicknamed 'the Hick from French Lick' and 'Larry Legend,' Bird is widely regarded as one of the greatest basketball players of all time",
           image="https://fadeawayworld.net/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTgwMzI0NDk3MjAxNzAyNzY0/larry-bird-i-wasnt-real-quick-and-i-wasnt-real-strong-some-guys-will-just-take-off-and-its-like-whoa-so-i-beat-them-with-my-mind-and-my-fundamentals.jpg",
           tier=1).save()

    Player(name="Magic Johnson",
           nickname="Magic",
           height=81,
           attributes={
                'offense': {
                    'layup': 93,
                    'post_shot': 90,
                    'mid_range': 87,
                    'three': 79,
                    'handles': 97,
                    'pass': 99,
                    'off_rebound': 74,
                    'dunk': 75
                },
               'defense': {
                    'def_rebound': 84,
                    'inside_defense': 80,
                    'outside_defense': 80,
                    'steal': 69,
                    'block': 62,
                    'post_defense': 80
                },
               'physical': {
                    'speed': 86,
                    'vertical': 84,
                    'strength': 76
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 67,
                   'shoot_three': 57,
                   'pass': 99,
                   'attack_rim': 95,
                   'post_up': 76
               },
               'defense': {
                   'steal': 60,
                   'block': 60,
                   'intercept': 67
               }
           }, avatar="https://miro.medium.com/max/600/0*-1Xu3h__9dKnoAYK.jpg",
           description="Johnson's career achievements include three NBA MVP Awards, nine NBA Finals appearances, twelve All-Star games, and ten All-NBA First and Second Team nominations. He led the league in regular season assists four times, and is the NBA's all-time leader in average assists per game, at 11.2.",
           image="https://d.newsweek.com/en/full/1614084/newsweek-amplify-magic-johnson-nba-store.png",
           tier=1).save()

    Player(name="Hakeem Olajuwon",
           nickname="The Dream",
           height=83,
           attributes={
                'offense': {
                    'layup': 78,
                    'post_shot': 98,
                    'mid_range': 77,
                    'three': 63,
                    'handles': 61,
                    'pass': 60,
                    'off_rebound': 92,
                    'dunk': 95
                },
               'defense': {
                    'def_rebound': 95,
                    'inside_defense': 99,
                    'outside_defense': 49,
                    'steal': 65,
                    'block': 88,
                    'post_defense': 99
                },
               'physical': {
                    'speed': 53,
                    'vertical': 60,
                    'strength': 88
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 57,
                   'shoot_three': 37,
                   'pass': 60,
                   'attack_rim': 99,
                   'post_up': 99
               },
               'defense': {
                   'steal': 60,
                   'block': 80,
                   'intercept': 59
               }
           }, avatar="https://i.guim.co.uk/img/media/58fcd5a6270acc3d7f72f150c476765bf39f924d/0_202_3589_2152/3589.jpg?width=700&quality=85&auto=format&fit=max&s=20dd508fa9848d088ffc4fbc6b81c58c",
           description="Despite very nearly being traded during a bitter contract dispute before the 1992–93 season, he remained in Houston. He became the first non-American to be an All-Star and start in an All-Star Game, the first non-American to win NBA MVP, the first non-American to win NBA Defensive Player of the Year, and in the 1993–94 season, he became the only player in NBA history to win the NBA MVP, Defensive Player of the Year, and Finals MVP awards in the same season.",
           image="https://cdn.britannica.com/19/200219-050-A33962F1/Hakeem-Olajuwon-1994.jpg",
           tier=1).save()
    Player(name="Kobe Bryant",
           nickname="Mamba",
           height=78,
           attributes={
                'offense': {
                    'layup': 98,
                    'post_shot': 74,
                    'mid_range': 94,
                    'three': 79,
                    'handles': 89,
                    'pass': 78,
                    'off_rebound': 55,
                    'dunk': 95
                },
               'defense': {
                    'def_rebound': 59,
                    'inside_defense': 68,
                    'outside_defense': 95,
                    'steal': 77,
                    'post_defense': 68,
                    'block': 51
                },
               'physical': {
                    'speed': 88,
                    'vertical': 88,
                    'strength': 75
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 90,
                   'shoot_three': 70,
                   'pass': 40,
                   'attack_rim': 90,
                   'post_up': 86
               },
               'defense': {
                   'steal': 75,
                   'block': 60,
                   'intercept': 80
               }
           }, avatar="https://live-production.wcms.abc-cdn.net.au/6a0e2b28bb4567afb28e6d1d8aed521d?impolicy=wcms_crop_resize&cropH=1688&cropW=3000&xPos=0&yPos=77&width=862&height=485",
           description="Widely regarded as one of the greatest basketball players of all time Bryant won five NBA championships, was an 18-time All-Star, a 15-time member of the All-NBA Team, a 12-time member of the All-Defensive Team, the 2008 NBA Most Valuable Player (MVP), and a two-time NBA Finals MVP.",
           image="https://cdn.bleacherreport.net/images_root/slides/photos/000/368/570/102184753_original.jpg?1283212258",
           tier=1).save()

    Player(name="Shaquille O'Neal",
           nickname="Diesel",
           height=84,
           attributes={
                'offense': {
                    'layup': 89,
                    'post_shot': 97,
                    'mid_range': 35,
                    'three': 26,
                    'handles': 64,
                    'pass': 77,
                    'off_rebound': 98,
                    'dunk': 99
                },
               'defense': {
                    'def_rebound': 97,
                    'inside_defense': 95,
                    'outside_defense': 49,
                    'steal': 74,
                    'post_defense': 49,
                    'block': 95
                },
               'physical': {
                    'speed': 76,
                    'vertical': 80,
                    'strength': 99
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 30,
                   'shoot_three': 10,
                   'pass': 50,
                   'attack_rim': 99,
                   'post_up': 99
               },
               'defense': {
                   'steal': 40,
                   'block': 70,
                   'intercept': 45
               }
           }, avatar="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTZmBYy9bn0ot_UkgrlgYJANVBNbEmIUkLMQ&usqp=CAU",
           description="O'Neal was drafted by the Orlando Magic with the first overall pick in the 1992 NBA draft. He quickly became one of the best centers in the league, winning Rookie of the Year in 1992–93 and leading his team to the 1995 NBA Finals. After four years with the Magic, O'Neal signed as a free agent with the Los Angeles Lakers. They won three consecutive championships in 2000, 2001, and 2002.",
           image="https://www.basketballnetwork.net/app/uploads/2021/05/shaq-copy-4.jpg",
           tier=1).save()

    Player(name="Kevin Garnett",
           nickname="Big Ticket",
           height=83,
           attributes={
                'offense': {
                    'layup': 82,
                    'post_shot': 89,
                    'mid_range': 94,
                    'three': 69,
                    'handles': 70,
                    'pass': 68,
                    'off_rebound': 93,
                    'dunk': 88
                },
               'defense': {
                    'def_rebound': 94,
                    'inside_defense': 97,
                    'post_defense': 97,
                    'outside_defense': 61,
                    'block': 80,
                    'steal': 65
                },
               'physical': {
                    'speed': 87,
                    'vertical': 87,
                    'strength': 88
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 70,
                   'shoot_three': 30,
                   'pass': 40,
                   'attack_rim': 80,
                   'post_up': 85
               },
               'defense': {
                   'steal': 60,
                   'block': 75,
                   'intercept': 65
               }
           }, avatar="https://cdn.bleacherreport.net/images_root/slides/photos/000/739/416/108623866_original.jpg?1298304188",
           description="Kevin Garnett is an American former professional basketball player who played for 21 seasons in the National Basketball Association (NBA). Known for his intensity, defensive ability, and versatility, Garnett is considered one of the greatest power forwards of all time.",
           image="https://sportshub.cbsistatic.com/i/r/2021/11/10/a6c845b1-9c30-415f-87af-d74d4169896f/thumbnail/1200x675/c522ef80fee9ee3cf13ecdfc0244d4eb/kevin-garnett.jpg",
           tier=1).save()

    Player(name="Steph Curry",
           nickname="Chef Curry",
           height=74,
           attributes={
                'offense': {
                    'layup': 97,
                    'post_shot': 52,
                    'mid_range': 93,
                    'three': 99,
                    'handles': 97,
                    'pass': 96,
                    'off_rebound': 93,
                    'dunk': 36
                },
               'defense': {
                    'def_rebound': 53,
                    'inside_defense': 30,
                    'post_defense': 30,
                    'outside_defense': 82,
                    'block': 37,
                    'steal': 77
                },
               'physical': {
                    'speed': 85,
                    'vertical': 78,
                    'strength': 48
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 70,
                   'shoot_three': 99,
                   'pass': 75,
                   'attack_rim': 80,
                   'post_up': 20
               },
               'defense': {
                   'steal': 70,
                   'block': 30,
                   'intercept': 40
               }
           }, avatar="https://static01.nyt.com/images/2019/11/01/sports/01CURRYalert/01CURRYalert-mobileMasterAt3x.jpg",
           description="In 2014–15, Curry won his first NBA Most Valuable Player award and led the Warriors to their first championship since 1975. The following season, he became the first player in NBA history to be elected MVP by a unanimous vote and to lead the league in scoring while shooting above 50–40–90. That same year, the Warriors broke the record for the most wins in an NBA season en route to reaching the 2016 NBA Finals, which they lost to the Cleveland Cavaliers in seven games.",
           image="https://s.hdnux.com/photos/01/17/15/02/20762796/14/rawImage.jpg",
           tier=1).save()

    Player(name="Kevin Durant",
           nickname="KD",
           height=83,
           attributes={
                'offense': {
                    'layup': 94,
                    'post_shot': 88,
                    'mid_range': 98,
                    'three': 88,
                    'handles': 86,
                    'pass': 79,
                    'off_rebound': 32,
                    'dunk': 85
                },
               'defense': {
                    'def_rebound': 69,
                    'inside_defense': 70,
                    'post_defense': 70,
                    'outside_defense': 86,
                    'block': 66,
                    'steal': 58
                },
               'physical': {
                    'speed': 80,
                    'vertical': 77,
                    'strength': 63
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 70,
                   'shoot_three': 80,
                   'pass': 40,
                   'attack_rim': 80,
                   'post_up': 50
               },
               'defense': {
                   'steal': 60,
                   'block': 50,
                   'intercept': 45
               }
           }, avatar="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHkkdj1b_U9TuTtAq4gRfxUTyokprM44yD9A&usqp=CAU",
           description="As a professional, he has won two NBA championships, an NBA Most Valuable Player Award, two Finals MVP Awards, two NBA All-Star Game Most Valuable Player Awards, four NBA scoring titles, the NBA Rookie of the Year Award, been named to nine All-NBA teams (including six First Teams), and selected 12 times as an NBA All-Star.",
           image="https://www.si.com/.image/ar_4:3%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTg1NTEzODAyMzE2MzkxNTg1/usatsi_16965380_168388303_lowres.jpg",
           tier=1).save()

    Player(name="Joel Embiid",
           nickname="The Process",
           height=84,
           attributes={
                'offense': {
                    'layup': 87,
                    'post_shot': 92,
                    'mid_range': 80,
                    'three': 82,
                    'handles': 57,
                    'pass': 55,
                    'off_rebound': 75,
                    'dunk': 90
                },
               'defense': {
                    'def_rebound': 90,
                    'inside_defense': 96,
                    'post_defense': 96,
                    'outside_defense': 64,
                    'block': 78,
                    'steal': 49
                },
               'physical': {
                    'speed': 69,
                    'vertical': 68,
                    'strength': 95
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 70,
                   'shoot_three': 50,
                   'pass': 35,
                   'attack_rim': 80,
                   'post_up': 95
               },
               'defense': {
                   'steal': 50,
                   'block': 90,
                   'intercept': 36
               }
           }, avatar="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSv0KliYvyfNXV3FZI_wLAzvjFM5eb1pwsGUQ&usqp=CAU",
           description="Joel Embiid is a Cameroonian professional basketball player for the Philadelphia 76ers of the National Basketball Association (NBA). After one year of college basketball with the Kansas Jayhawks, he was drafted with the third overall pick in the 2014 NBA draft by the 76ers.",
           image="https://www.si.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTg2ODIwOTk1NDc3MTUzMjYz/joel-embiid.jpg",
           tier=1).save()

    Player(name="Kawhi Leonard",
           nickname="The Claw",
           height=81,
           attributes={
                'offense': {
                    'layup': 93,
                    'post_shot': 88,
                    'mid_range': 87,
                    'three': 83,
                    'handles': 86,
                    'pass': 82,
                    'off_rebound': 70,
                    'dunk': 86
                },
               'defense': {
                    'def_rebound': 72,
                    'inside_defense': 83,
                    'post_defense': 83,
                    'outside_defense': 97,
                    'block': 50,
                    'steal': 92
                },
               'physical': {
                    'speed': 81,
                    'vertical': 79,
                    'strength': 79
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 78,
                   'shoot_three': 60,
                   'pass': 50,
                   'attack_rim': 87,
                   'post_up': 67
               },
               'defense': {
                   'steal': 90,
                   'block': 76,
                   'intercept': 78
               }
           }, avatar="https://www.si.com/.image/t_share/MTY4NDg4NzE5OTk1NjQzNzM1/kawhi-leonard.jpg",
           description="With the Spurs, Leonard won an NBA championship in 2014, where he was named the Finals Most Valuable Player. After seven seasons with the Spurs, Leonard was traded to the Toronto Raptors in 2018. In 2019, he led the Raptors to their first NBA championship in franchise history and won his second Finals MVP award",
           image="https://image.cnbcfm.com/api/v1/image/106797780-1605566208011-gettyimages-1272714063-_dd15420_20200915104212178.jpeg?v=1605566326",
           tier=1).save()

    Player(name="Scottie Pippen",
           nickname="Pip",
           height=80,
           attributes={
                'offense': {
                    'layup': 88,
                    'post_shot': 80,
                    'mid_range': 84,
                    'three': 87,
                    'handles': 80,
                    'pass': 89,
                    'off_rebound': 66,
                    'dunk': 91
                },
               'defense': {
                    'def_rebound': 69,
                    'inside_defense': 79,
                    'post_defense': 79,
                    'outside_defense': 98,
                    'block': 70,
                    'steal': 79
                },
               'physical': {
                    'speed': 87,
                    'vertical': 84,
                    'strength': 80
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 60,
                   'shoot_three': 50,
                   'pass': 50,
                   'attack_rim': 89,
                   'post_up': 60
               },
               'defense': {
                   'steal': 90,
                   'block': 76,
                   'intercept': 78
               }
           }, avatar="https://heavy.com/wp-content/uploads/2020/04/gettyimages-288433-e1587404676462.jpg?quality=65&strip=all&w=780",
           description="Considered one of the greatest small forwards of all time, Pippen was named to the NBA All-Defensive First Team eight consecutive times and the All-NBA First Team three times. He was a seven-time NBA All-Star and was the NBA All-Star Game MVP in 1994. He was named one of the 50 Greatest Players in NBA History during the 1996–97 season, and is one of four players to have his jersey retired by the Chicago Bulls",
           image="https://www.nba.com/bulls/sites/bulls/files/200511_pippen_cp.jpg",
           tier=1).save()

    Player(name="Dwyane Wade",
           nickname="Flash",
           height=76,
           attributes={
                'offense': {
                    'layup': 95,
                    'post_shot': 79,
                    'mid_range': 89,
                    'three': 79,
                    'handles': 89,
                    'pass': 95,
                    'off_rebound': 59,
                    'dunk': 95
                },
               'defense': {
                    'def_rebound': 61,
                    'inside_defense': 67,
                    'post_defense': 67,
                    'outside_defense': 94,
                    'block': 59,
                    'steal': 79
                },
               'physical': {
                    'speed': 97,
                    'vertical': 85,
                    'strength': 79
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 70,
                   'shoot_three': 50,
                   'pass': 60,
                   'attack_rim': 99,
                   'post_up': 45
               },
               'defense': {
                   'steal': 75,
                   'block': 50,
                   'intercept': 69
               }
           }, avatar="https://www.thefamouspeople.com/profiles/images/dwyane-wade-7.jpg",
           description="Dwyane Wade is an American former professional basketball player. Wade spent the majority of his 16-year career playing for the Miami Heat of the National Basketball Association (NBA) and won three NBA championships, was a 13-time NBA All-Star, an 8-time member of the All-NBA Team, and a 3-time member of the All-Defensive Team.",
           image="https://static01.nyt.com/images/2018/09/17/sports/17wade/merlin_136020240_d603bb45-5616-41df-9230-6cb59368b979-superJumbo.jpg",
           tier=1).save()

    Player(name="Dirk Nowitzki",
           nickname="Flying Dutchman",
           height=84,
           attributes={
                'offense': {
                    'layup': 78,
                    'post_shot': 99,
                    'mid_range': 89,
                    'three': 90,
                    'handles': 60,
                    'pass': 69,
                    'off_rebound': 83,
                    'dunk': 75
                },
               'defense': {
                    'def_rebound': 84,
                    'inside_defense': 80,
                    'post_defense': 80,
                    'outside_defense': 43,
                    'block': 69,
                    'steal': 50
                },
               'physical': {
                    'speed': 46,
                    'vertical': 40,
                    'strength': 80
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 80,
                   'shoot_three': 80,
                   'pass': 50,
                   'attack_rim': 69,
                   'post_up': 96
               },
               'defense': {
                   'steal': 40,
                   'block': 40,
                   'intercept': 35
               }
           }, avatar="https://dsf-img-storage.s3.us-east-2.amazonaws.com/wp-content/uploads/2017/01/05130731/Mavs-Fanatic-10-of-52-e1510873435146.jpg",
           description="Nowitzki is the only player ever to play for a single NBA franchise for 21 seasons. He is a 14-time All-Star, a 12-time All-NBA Team member,[10] the first European player to start in an All-Star Game, and the first European player to receive the NBA Most Valuable Player Award. Nowitzki is the highest-scoring foreign-born player in NBA history.",
           image="https://th.bing.com/th/id/R.40ef4aa877f401f06511757a4992b69e?rik=1lgAORZN%2fgXNLA&riu=http%3a%2f%2fimg.bleacherreport.net%2fimg%2fimages%2fphotos%2f002%2f821%2f208%2fhi-res-94543bac4bf7dee10e5ffecbf8d2037a_crop_exact.jpg%3fw%3d1200%26h%3d1200%26q%3d75&ehk=uec%2bDuybaNxpmG%2fMcDFq8J8LTy77z2xaN2Z6k4oWC%2bM%3d&risl=&pid=ImgRaw&r=0",
           tier=1).save()

    Player(name="Allen Iverson",
           nickname="The Answer",
           height=72,
           attributes={
                'offense': {
                    'layup': 98,
                    'post_shot': 60,
                    'mid_range': 87,
                    'three': 79,
                    'handles': 97,
                    'pass': 90,
                    'off_rebound': 49,
                    'dunk': 65
                },
               'defense': {
                    'def_rebound': 55,
                    'inside_defense': 35,
                    'post_defense': 35,
                    'outside_defense': 88,
                    'block': 39,
                    'steal': 95
                },
               'physical': {
                    'speed': 97,
                    'vertical': 97,
                    'strength': 69
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 70,
                   'shoot_three': 50,
                   'pass': 65,
                   'attack_rim': 90,
                   'post_up': 45
               },
               'defense': {
                   'steal': 90,
                   'block': 40,
                   'intercept': 84
               }
           }, avatar="http://assets.rappler.com/612F469A6EA84F6BAE882D2B94A4B421/img/FCDA36695F0C4003803EC177E3F4269F/allen-iverson-sixers-epa-file-20140801_FCDA36695F0C4003803EC177E3F4269F.jpg",
           description="Allen Iverson is an American former professional basketball player. Nicknamed 'the Answer' and 'AI', he played 14 seasons in the National Basketball Association (NBA) at both the shooting guard and point guard positions. Iverson won NBA Rookie of the Year Award in 1997 and was an 11-time NBA All-Star, won the All-Star game MVP award in 2001 and 2005, and was the NBA's Most Valuable Player (MVP) in 2001. He was inducted into the Naismith Memorial Basketball Hall of Fame in 2016. In October 2021, Iverson was honored as one of the league's greatest players of all time by being named to the NBA 75th Anniversary Team.",
           image="https://buysidesports.com/wp-content/uploads/2020/06/allen-iverson-surprising-facts-1-e1596251286150.jpeg",
           tier=1).save()

    Player(name="Chris Paul",
           nickname="CP3",
           height=72,
           attributes={
                'offense': {
                    'layup': 92,
                    'post_shot': 55,
                    'mid_range': 86,
                    'three': 82,
                    'handles': 94,
                    'pass': 95,
                    'off_rebound': 37,
                    'dunk': 27
                },
               'defense': {
                    'def_rebound': 63,
                    'inside_defense': 65,
                    'post_defense': 65,
                    'outside_defense': 93,
                    'block': 32,
                    'steal': 85
                },
               'physical': {
                    'speed': 84,
                    'vertical': 78,
                    'strength': 58
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 90,
                   'shoot_three': 70,
                   'pass': 80,
                   'attack_rim': 69,
                   'post_up': 30
               },
               'defense': {
                   'steal': 90,
                   'block': 40,
                   'intercept': 99
               }
           }, avatar="https://img.bleacherreport.net/img/slides/photos/003/499/468/459774635-chris-paul-of-the-los-angeles-clippers-looks-on-against_crop_exact.jpg?w=2975&h=2048&q=85",
           description="Christopher Paul nicknamed 'CP3', is an American professional basketball player who plays for the Phoenix Suns of the National Basketball Association (NBA). Paul is a point guard who has won the NBA Rookie of the Year Award, an NBA All-Star Game Most Valuable Player Award, two Olympic gold medals, and led the NBA in assists four times and steals a record six times. He has also been selected to twelve NBA All-Star teams, ten All-NBA teams, and nine NBA All-Defensive teams. In 2021, he was named to the NBA 75th Anniversary Team.",
           image="https://ewscripps.brightspotcdn.com/02/fd/2842c30f426e80a52e800548b7b7/ap21165821777548.jpg",
           tier=1).save()

    Player(name="Kyrie Irving",
           nickname="Uncle Drew",
           height=74,
           attributes={
                'offense': {
                    'layup': 96,
                    'post_shot': 64,
                    'mid_range': 97,
                    'three': 90,
                    'handles': 99,
                    'pass': 84,
                    'off_rebound': 36,
                    'dunk': 30
                },
               'defense': {
                    'def_rebound': 43,
                    'inside_defense': 32,
                    'post_defense': 32,
                    'outside_defense': 62,
                    'block': 45,
                    'steal': 66
                },
               'physical': {
                    'speed': 86,
                    'vertical': 81,
                    'strength': 37
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 80,
                   'shoot_three': 80,
                   'pass': 50,
                   'attack_rim': 94,
                   'post_up': 45
               },
               'defense': {
                   'steal': 65,
                   'block': 30,
                   'intercept': 45
               }
           }, avatar="https://nypost.com/wp-content/uploads/sites/2/2020/02/kyrie-irving-4.jpg?quality=80&strip=all",
           description="Kyrie Irving is an American professional basketball player for the Brooklyn Nets of the National Basketball Association (NBA). He was named the Rookie of the Year after being selected by the Cleveland Cavaliers with the first overall pick in the 2011 NBA draft. A seven-time All-Star and three-time member of the All-NBA Team, he won an NBA championship with the Cavaliers in 2016.",
           image="https://static01.nyt.com/images/2021/10/08/lens/08nba-kyrie-01/merlin_195444735_cfee78bc-ed13-4a08-9267-501cc59d7a9c-superJumbo.jpg",
           tier=1).save()

    Player(name="Kareem Abdul-Jabbar",
           nickname="Cap",
           height=86,
           attributes={
                'offense': {
                    'layup': 84,
                    'post_shot': 94,
                    'mid_range': 88,
                    'three': 30,
                    'handles': 48,
                    'pass': 58,
                    'off_rebound': 95,
                    'dunk': 95
                },
               'defense': {
                    'def_rebound': 96,
                    'inside_defense': 96,
                    'post_defense': 96,
                    'outside_defense': 37,
                    'block': 88,
                    'steal': 56
                },
               'physical': {
                    'speed': 78,
                    'vertical': 68,
                    'strength': 83
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 50,
                   'shoot_three': 20,
                   'pass': 40,
                   'attack_rim': 99,
                   'post_up': 99
               },
               'defense': {
                   'steal': 50,
                   'block': 95,
                   'intercept': 65
               }
           }, avatar="https://fadeawayworld.net/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTg0NDg1MzE4NzEwMjczMTQ0/kareem-abdul-jabbar-iso-1981.jpg",
           description="Kareem Abdul-Jabbar is an American former professional basketball player for the Milwaukee Bucks and the Los Angeles Lakers. During his career as a center, Abdul-Jabbar was a record six-time NBA Most Valuable Player (MVP), a record 19-time NBA All-Star, a 15-time All-NBA selection, and an 11-time NBA All-Defensive Team member. A member of six NBA championship teams as a player and two more as an assistant coach, Abdul-Jabbar twice was voted NBA Finals MVP.",
           image="https://www.doubleclutch.uk/wp-content/uploads/2020/04/Kareem_Abdul_Jabbar-e1587670066296.jpg",
           tier=1).save()

    Player(name="Carmelo Anthony",
           nickname="Melo",
           height=80,
           attributes={
                'offense': {
                    'layup': 89,
                    'post_shot': 95,
                    'mid_range': 97,
                    'three': 80,
                    'handles': 94,
                    'pass': 84,
                    'off_rebound': 45,
                    'dunk': 85
                },
               'defense': {
                    'def_rebound': 78,
                    'inside_defense': 73,
                    'post_defense': 73,
                    'outside_defense': 72,
                    'block': 68,
                    'steal': 78
                },
               'physical': {
                    'speed': 92,
                    'vertical': 85,
                    'strength': 82
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 75,
                   'shoot_three': 60,
                   'pass': 30,
                   'attack_rim': 80,
                   'post_up': 95
               },
               'defense': {
                   'steal': 40,
                   'block': 60,
                   'intercept': 39
               }
           }, avatar="https://a.espncdn.com/combiner/i?img=%2Fphoto%2F2021%2F0224%2Fr818864_1296x729_16%2D9.jpg",
           description="Carmelo Anthony is an American professional basketball player for the Los Angeles Lakers of the National Basketball Association (NBA). He has been named an NBA All-Star ten times and an All-NBA Team member six times. He played college basketball for the Syracuse Orange, winning a national championship as a freshman in 2003 while being named the NCAA Tournament's Most Outstanding Player. During the NBA's 75th anniversary, he was named one of the 75 Greatest Players in NBA History.[2]",
           image="https://vip.nypost.com/wp-content/uploads/sites/2/2020/03/carmelo-anthony.jpg?quality=90&strip=all",
           tier=1).save()

    Player(name="Klay Thompson",
           nickname="Splash Brother",
           height=78,
           attributes={
                'offense': {
                    'layup': 88,
                    'post_shot': 78,
                    'mid_range': 94,
                    'three': 97,
                    'handles': 76,
                    'pass': 77,
                    'off_rebound': 36,
                    'dunk': 65
                },
               'defense': {
                    'def_rebound': 47,
                    'inside_defense': 64,
                    'post_defense': 64,
                    'outside_defense': 91,
                    'block': 51,
                    'steal': 59
                },
               'physical': {
                    'speed': 69,
                    'vertical': 67,
                    'strength': 55
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 80,
                   'shoot_three': 90,
                   'pass': 30,
                   'attack_rim': 70,
                   'post_up': 40
               },
               'defense': {
                   'steal': 80,
                   'block': 50,
                   'intercept': 76
               }
           }, avatar="https://cdn.nba.com/manage/2020/11/klay-thompson-iso-1568x1045.jpg",
           description="Klay Thompson is an American professional basketball player for the Golden State Warriors of the National Basketball Association (NBA). He is credited as one of the greatest shooters in NBA history.[2][3] A three-time NBA champion with the Warriors, he is a five-time NBA All-Star and a two-time All-NBA Third Team honoree. He has also been named to the NBA All-Defensive Second Team.",
           image="https://www.nbcsports.com/sites/rsnunited/files/article/hero/Klay-Thompson-Shooting-USATSI-17087442.jpg",
           tier=1).save()

    Player(name="Chris Bosh",
           nickname="CB4",
           height=83,
           attributes={
                'offense': {
                    'layup': 88,
                    'post_shot': 80,
                    'mid_range': 84,
                    'three': 79,
                    'handles': 65,
                    'pass': 69,
                    'off_rebound': 87,
                    'dunk': 85
                },
               'defense': {
                    'def_rebound': 87,
                    'inside_defense': 85,
                    'post_defense': 85,
                    'outside_defense': 60,
                    'block': 78,
                    'steal': 59
                },
               'physical': {
                    'speed': 48,
                    'vertical': 65,
                    'strength': 85
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 70,
                   'shoot_three': 50,
                   'pass': 55,
                   'attack_rim': 88,
                   'post_up': 80
               },
               'defense': {
                   'steal': 60,
                   'block': 85,
                   'intercept': 45
               }
           }, avatar="http://images.thepostgame.com/assets/public/styles/slideshow_image/public/GettyImages-150590242-compressor.jpg",
           description="While at Toronto, Bosh became a five-time NBA All-Star, was named to the All-NBA Second Team once, played for the U.S. national team (with whom he won a gold medal at the 2008 Summer Olympics), and supplanted former fan favorite Vince Carter as the face and leader of the Raptors franchise. In the 2006–07 season, Bosh led the Raptors to their first playoff appearance in five years and their first-ever division title. He left Toronto in 2010 as the franchise's all-time leader in points, rebounds, blocks, and minutes played.",
           image="https://www.cleveland.com/resizer/MH_H8zEUC6FWyOtbQDo1bzWCuaY=/1280x0/smart/advancelocal-adapter-image-uploads.s3.amazonaws.com/image.cleveland.com/home/cleve-media/width2048/img/cavs_impact/photo/chris-bosh-2f5fc84c60ad8d8f.jpg",
           tier=1).save()

    Player(name="Bill Russell",
           nickname="Russ",
           height=82,
           attributes={
                'offense': {
                    'layup': 76,
                    'post_shot': 65,
                    'mid_range': 45,
                    'three': 29,
                    'handles': 45,
                    'pass': 78,
                    'off_rebound': 97,
                    'dunk': 95
                },
               'defense': {
                    'def_rebound': 98,
                    'inside_defense': 98,
                    'post_defense': 98,
                    'outside_defense': 55,
                    'block': 99,
                    'steal': 72
                },
               'physical': {
                    'speed': 84,
                    'vertical': 88,
                    'strength': 94
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 30,
                   'shoot_three': 10,
                   'pass': 60,
                   'attack_rim': 80,
                   'post_up': 75
               },
               'defense': {
                   'steal': 70,
                   'block': 99,
                   'intercept': 87
               }
           }, avatar="https://www.giantbomb.com/a/uploads/square_medium/14/141373/2681643-0711686871-dna06.jpg",
           description="A five-time NBA Most Valuable Player and a 12-time All-Star, he was the centerpiece of the Celtics dynasty that won eleven NBA championships during his 13-year career. Russell and Henri Richard of the National Hockey League are tied for the record of the most championships won by an athlete in a North American sports league. Russell led the San Francisco Dons to two consecutive NCAA championships in 1955 and 1956, and he captained the gold-medal winning U.S. national basketball team at the 1956 Summer Olympics.",
           image="https://s-i.huffpost.com/gadgets/slideshows/304026/slide_304026_2589444_free.jpg",
           tier=1).save()

    Player(name="Dennis Rodman",
           nickname="The Worm",
           height=79,
           attributes={
                'offense': {
                    'layup': 55,
                    'post_shot': 48,
                    'mid_range': 65,
                    'three': 62,
                    'handles': 45,
                    'pass': 61,
                    'off_rebound': 99,
                    'dunk': 90
                },
               'defense': {
                    'def_rebound': 98,
                    'inside_defense': 98,
                    'post_defense': 98,
                    'outside_defense': 77,
                    'block': 50,
                    'steal': 57
                },
               'physical': {
                    'speed': 78,
                    'vertical': 88,
                    'strength': 86
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 30,
                   'shoot_three': 10,
                   'pass': 30,
                   'attack_rim': 40,
                   'post_up': 60
               },
               'defense': {
                   'steal': 70,
                   'block': 99,
                   'intercept': 87
               }
           }, avatar="https://images.7news.com.au/publication/C-1046789/59774a3762246f68c2bceca98719361c6a8d46cc.jpg?imwidth=650&impolicy=sevennews_v2",
           description="Rodman played at the small forward position in his early years before becoming a power forward. He earned NBA All-Defensive First Team honors seven times and won the NBA Defensive Player of the Year Award twice. He also led the NBA in rebounds per game for a record seven consecutive years and won five NBA championships.",
           image="https://www.rollingstone.com/wp-content/uploads/2020/04/dennis-rodman-tattoo-t-shirt.jpg",
           tier=1).save()

    Player(name="Isiah Thomas",
           nickname="Zeke",
           height=73,
           attributes={
                'offense': {
                    'layup': 97,
                    'post_shot': 29,
                    'mid_range': 84,
                    'three': 72,
                    'handles': 97,
                    'pass': 94,
                    'off_rebound': 35,
                    'dunk': 65
                },
               'defense': {
                    'def_rebound': 45,
                    'inside_defense': 40,
                    'post_defense': 40,
                    'outside_defense': 81,
                    'block': 35,
                    'steal': 71
                },
               'physical': {
                    'speed': 92,
                    'vertical': 74,
                    'strength': 60
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 80,
                   'shoot_three': 65,
                   'pass': 79,
                   'attack_rim': 90,
                   'post_up': 40
               },
               'defense': {
                   'steal': 85,
                   'block': 30,
                   'intercept': 74
               }
           }, avatar="https://th.bing.com/th/id/OIP.xkNKvPjHyXt-whUQbzK6bwHaEK?pid=ImgDet&rs=1",
           description="A point guard, the 12-time NBA All-Star was named one of the 50 Greatest Players in NBA History as well as the 75 Greatest Players, and inducted into the Naismith Memorial Basketball Hall of Fame. He played his entire professional career for the Detroit Pistons of the National Basketball Association (NBA).",
           image="https://th.bing.com/th/id/R.57c9dbd49ba36969e21aef35228a4467?rik=7lGk1xMz0OFqGA&riu=http%3a%2f%2fimages.complex.com%2fcomplex%2fimage%2fupload%2fc_limit%2cw_680%2ff_auto%2cfl_lossy%2cpg_1%2cq_auto%2fp7pkha6ef63hoq2vyjhr.jpg&ehk=wkCsEHX%2foJ4yXQ3PyY%2bzbeufl26SuWgU%2ffeSJL0bsnQ%3d&risl=&pid=ImgRaw&r=0",
           tier=1).save()

    Player(name="Patrick Ewing",
           nickname="Big Pat",
           height=84,
           attributes={
                'offense': {
                    'layup': 69,
                    'post_shot': 98,
                    'mid_range': 83,
                    'three': 35,
                    'handles': 40,
                    'pass': 64,
                    'off_rebound': 67,
                    'dunk': 95
                },
               'defense': {
                    'def_rebound': 92,
                    'inside_defense': 94,
                    'post_defense': 94,
                    'outside_defense': 35,
                    'block': 90,
                    'steal': 59
                },
               'physical': {
                    'speed': 45,
                    'vertical': 46,
                    'strength': 92
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 40,
                   'shoot_three': 10,
                   'pass': 50,
                   'attack_rim': 78,
                   'post_up': 99
               },
               'defense': {
                   'steal': 55,
                   'block': 89,
                   'intercept': 59
               }
           }, avatar="https://comicvine.gamespot.com/a/uploads/square_medium/11/114183/5167058-20150805-1-ewing.jpg",
           description="He had a seventeen-year NBA career, predominantly playing for the New York Knicks, where he was an eleven-time all-star and named to seven All-NBA teams. The Knicks appeared in the NBA Finals twice (1994 and 1999) during his tenure. He won Olympic gold medals as a member of the 1984 and 1992 United States men's Olympic basketball teams. Ewing was selected as one of the 50 Greatest Players in NBA History in 1996 and as one of the 75 Greatest Players in NBA History in 2021.",
           image="https://images.pristineauction.com/129/1290754/main_1566511888-Patrick-Ewing-Signed-New-York-Knicks-16x20-Photo-Steiner-COA-PristineAuction.com.jpg",
           tier=1).save()

    Player(name="Tony Parker",
           nickname="T.P",
           height=74,
           attributes={
                'offense': {
                    'layup': 97,
                    'post_shot': 58,
                    'mid_range': 87,
                    'three': 73,
                    'handles': 95,
                    'pass': 94,
                    'off_rebound': 30,
                    'dunk': 30
                },
               'defense': {
                    'def_rebound': 47,
                    'inside_defense': 54,
                    'post_defense': 54,
                    'outside_defense': 80,
                    'block': 35,
                    'steal': 85
                },
               'physical': {
                    'speed': 99,
                    'vertical': 85,
                    'strength': 50
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 80,
                   'shoot_three': 70,
                   'pass': 60,
                   'attack_rim': 75,
                   'post_up': 20
               },
               'defense': {
                   'steal': 75,
                   'block': 20,
                   'intercept': 67
               }
           }, avatar="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQK-dEHtfzaUKXkUxDBemnOR80cl7UmRDB-SA&usqp=CAU",
           description="Parker was named to six NBA All-Star games, three All-NBA Second Teams, an All-NBA Third Team and was named MVP of the 2007 NBA Finals. He was also a member of the All-Rookie Second Team and had his No. 9 retired by the Spurs. He is widely regarded as one of the greatest European players of all time.",
           image="https://s.hdnux.com/photos/01/11/36/32/19261106/14/rawImage.jpg",
           tier=1).save()

    Player(name="Manu Ginobili",
           nickname="Gino",
           height=78,
           attributes={
                'offense': {
                    'layup': 92,
                    'post_shot': 65,
                    'mid_range': 80,
                    'three': 84,
                    'handles': 86,
                    'pass': 82,
                    'off_rebound': 52,
                    'dunk': 50
                },
               'defense': {
                    'def_rebound': 62,
                    'inside_defense': 45,
                    'post_defense': 45,
                    'outside_defense': 75,
                    'block': 51,
                    'steal': 70
                },
               'physical': {
                    'speed': 80,
                    'vertical': 67,
                    'strength': 43
                }
           }, tendencies={
               'offense': {
                   'shoot_mid': 80,
                   'shoot_three': 60,
                   'pass': 40,
                   'attack_rim': 80,
                   'post_up': 30
               },
               'defense': {
                   'steal': 65,
                   'block': 40,
                   'intercept': 67
               }
           }, avatar="https://img.bleacherreport.net/img/images/photos/003/100/456/hi-res-86e2d4eeda744238fcdd7b0fe590af27_crop_north.jpg?1412881622&w=3072&h=2048",
           description="Selected as the 57th overall pick in the 1999 NBA draft, Ginóbili joined the Spurs in 2002 and soon became a key player for the team. In addition to his four NBA championships, Ginóbili was named an All-Star in 2005 and 2011 and was selected twice for the All-NBA Third Team. In 2007–08, he was named the NBA Sixth Man of the Year. Ginóbili announced his retirement from the NBA on 27 August 2018.",
           image="https://media.newyorker.com/photos/5b845a96244246652b65882f/4:3/w_2559,h_1919,c_limit/Cunningham-Manu-Ginobili.jpg",
           tier=1).save()


def fallow(apps, schema_editor):
    Player = apps.get_model('blacktop', 'Player')
    Player.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('blacktop', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
