# Generated by Django 4.0.2 on 2022-02-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blacktop', '0001_initial'),
    ]

    operations = [
    ]
