# Generated by Django 4.0.2 on 2022-02-12 20:03

from django.db import migrations


def seed(apps, schema_editor):
    Squad = apps.get_model('blacktop', 'Squad')
    Squad(
        team_name="Miami Heat Big 3", players={"p1": 16, "p2": 2, "p3": 24}, wins=0, losses=0
    ).save()
    Squad(
        team_name="Show Time Lakers", players={"p1": 6, "p2": 8, "p3": 9}, wins=0, losses=0
    ).save()
    Squad(
        team_name="2018 Warriors", players={"p1": 11, "p2": 23, "p3": 12}, wins=0, losses=0
    ).save()
    Squad(
        team_name="Chicago Bulls 3", players={"p1": 1, "p2": 15, "p3": 26}, wins=0, losses=0
    ).save()
    Squad(
        team_name="San Antonio Spurs", players={"p1": 29, "p2": 30, "p3": 3}, wins=0, losses=0
    ).save()
    Squad(
        team_name="Celtics Big 3", players={"p1": 5, "p2": 10, "p3": 25}, wins=0, losses=0
    ).save()
    

def fallow(apps, schema_editor):
    Squad = apps.get_model('blacktop', 'Squad')
    Squad.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('blacktop', '0002_auto_20220214_0008'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
